[package]
name = "ex_tiberius_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "ex_tiberius_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.0"
lazy_static = "1.0"
tiberius = "0.3.2"